kind: pipeline
type: docker
name: default

steps:
  - name: download-deps
    image: clojure:tools-deps
    commands:
      - clojure -P

  - name: test
    image: clojure:tools-deps
    commands:
      - clojure -M:test

  - name: build
    image: clojure:tools-deps
    commands:
      - clojure -M:uberjar

  - name: publish
    image: plugins/docker
    repo: lutecethecrab/vega
