kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: clojure:tools-deps
    commands:
      - clojure -M:test

  - name: build
    image: clojure:tools-deps
    commands:
      - clojure -T:build uber
